#Get all users

GET http://localhost:5000/users

//gwt a single users
GET     http://localhost:5000/users/1

####
//register  user
//register
//login
//signup
###

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Phumudzo@gmail.com",
   "password": "123456789"
}


###
http://localhost:5000/booking
####
#GET ALL BOOKINGS FOR A USER
http://localhost:5000/2/booking
####
http://localhost:5000/listings
#####
# POST http://localhost:5000/posts
# content-type: application/json
# {
#     "title": "airbn clone",
#     "author": "Phumudzo",
# }